### ISSUE TITLE
ArgumentOutOfRangeException while adding a PrimaryCommand in the NavigationBar control by code

### ISSUE THREAD

**Issue by KevKevin** [unoplatform/uno.toolkit.ui#1150]
## Current behavior

With a simple NavigationBar I tryed to add a PrimaryCommand by code.
I tryed in the Loaded event and clicking a Button but always raise the ArgumentOutOfRangeException.
The only work around is to Add the AppBarButton after the InitializeComponent in the constructor of the Page.

## Expected behavior

Adding the AppBarButton any time.

## How to reproduce it (as minimally and precisely as possible)
- Create an empty app targetting windows
- Add a NavigationBar inside a Page
- Add a Button in the Page and in the Click event try to add an AppBarButton in the PrimaryCommands of the NavigationBar

Affected platform(s):

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [X] Windows

IDE:

- [X] Visual Studio 2022
- [ ] Visual Studio 2019
- [ ] Visual Studio Code
- [ ] Visual Studio for Mac
- [ ] Rider Windows
- [ ] Rider macOS

Attached a repo with the issue:
[UnoApp1.zip](https://github.com/user-attachments/files/15592681/UnoApp1.zip)

**Comment by agneszitte** [comment]
cc @kazo0

**Comment by Xiaoy312** [comment]
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values. (Parameter 'index')
  Source=WinRT.Runtime
  StackTrace:
   at ABI.System.Collections.Generic.IListMethods`1.SetAtHelper(IObjectReference obj, UInt32 index, T value)
   at ABI.System.Collections.Generic.IListMethods`1.Indexer_Set(IObjectReference obj, Int32 index, T value)
   at ABI.System.Collections.Generic.IList`1.global::System.Collections.Generic.IList<T>.set_Item(Int32 index, T value)
   at Uno.Toolkit.UI.NavigationBarPresenter.OnCommandsChanged(IObservableVector`1 sender, IVectorChangedEventArgs args, DependencyProperty prop) in Uno.Toolkit.UI\NavigationBarPresenter.cs:line 243
   at Uno.Toolkit.UI.NavigationBarPresenter.OnNavBarPrimaryCommandsChanged(IObservableVector`1 sender, IVectorChangedEventArgs args) in Uno.Toolkit.UI\NavigationBarPresenter.cs:line 212
   at Uno.Toolkit.UI.NavigationBarElementCollection.RaiseVectorChanged(CollectionChange change, Int32 changeIndex) in Uno.Toolkit.UI\NavigationBarElementCollection.cs:line 104
   at Uno.Toolkit.UI.NavigationBarElementCollection.Insert(Int32 index, ICommandBarElement item) in Uno.Toolkit.UI\NavigationBarElementCollection.cs:line 75
   at Uno.Toolkit.UI.NavigationBarElementCollection.Append(ICommandBarElement item) in Uno.Toolkit.UI\NavigationBarElementCollection.cs:line 43
   at Uno.Toolkit.UI.NavigationBarElementCollection.Add(ICommandBarElement item) in Uno.Toolkit.UI\NavigationBarElementCollection.cs:line 38
   at UnoApp1.MainPage.Button_Click(Object sender, RoutedEventArgs e) in D:\code\uno\tests\tlk1150\UnoApp1\MainPage.xaml.cs:line 18
   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e) in WinRT\_EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.cs:line 21
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e) in ABI.Microsoft.UI.Xaml\RoutedEventHandler.cs:line 136
```

https://github.com/unoplatform/uno.toolkit.ui/blob/6.0.0/src/Uno.Toolkit.UI/Controls/NavigationBar/NavigationBarPresenter.cs#L241-L249

@kazo0 you cant just sync up two collections like that. insert and changed are two different concepts:
```
var col1 = new List<int>(); // ItemInserted
col1.Insert(0, 00);
col1.Insert(1, 11);

var col2 = new List<int>(); // ItemChanged
col2[0] = 00; // throws out-of-range (there is no ore-existing item#0 in the list yet)
col2[1] = 11;
```
