### ISSUE TITLE
[Win][AncestralBinding] throws COMException

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno.toolkit.ui#1218]
## Current behavior
```xml
<ListView ItemsSource="{Binding Files, Mode=OneWay}">
	<ListView.ItemTemplate>
		<DataTemplate>
			<Button IsEnabled="{utu:AncestorBinding AncestorType=ListView, Path=DataContext.IsBusy}" />
```
<details>
<summary>throws COMException</summary>

```
System.Runtime.InteropServices.COMException (0x80004005)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
```
</details>

---OR---
```xml
<Page ...>
	<Button IsEnabled="{custom:AncestralBinding AncestorType=Page, Path=DataContext.IsBusy}" />
```
<details>
<summary>throws XamlParseException</summary>

```
Microsoft.UI.Xaml.Markup.XamlParseException: 'The text associated with this error code could not be found.

Failed to assign to property 'Microsoft.UI.Xaml.Controls.Control.IsEnabled' because the type 'Windows.Foundation.Object' cannot be assigned to the type 'Windows.Foundation.Boolean'. [Line: 14 Position: 11]'
```
</details>

throws exception.

## Expected behavior
^ should not throw any exception.

## How to reproduce it (as minimally and precisely as possible)
Nuget Package: Uno.Toolkit.WinUI@6.0.18
Affected platform(s): Windows

**Comment by Xiaoy312** [comment]
In AncestorBinding::ProvideValue, we are first returning a _default_ `null` value when the binding isnt ready to happen. For some dependency property, it would be illegal.
