### ISSUE TITLE
[uno][AncestorBinding] throws InvalidOperationException

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno.toolkit.ui#1219]
## Current behavior
```xml
<Page ...>
	<Button IsEnabled="{utu:AncestorBinding AncestorType=Page, Path=DataContext.IsBusy}" />
```
<details>
<summary>throws InvalidOperationException</summary>

```
System.InvalidOperationException: Failed to load ItemsRepeaterSelection.MainPage: System.NullReferenceException: Object reference not set to an instance of an object.
         at ItemsRepeaterSelection.MainPage.<>c.<InitializeComponent>b__6_4(Button c0, MainPage __that, NameScope __nameScope) in D:\code\uno\tests\tlk1194\ItemsRepeaterSelection\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_0240dbe7b7b29d4de0c9e16d14bff8f5.cs:line 86
         at Uno.UI.Helpers.Xaml.ApplyExtensions.GenericApply[TType,TArg1,TArg2](TType instance, TArg1 arg1, TArg2 arg2, Action`3 apply) in /__w/1/s/src/Uno.UI/UI/Xaml/Markup/ApplyExtensions.cs:line 58
         at ItemsRepeaterSelection.MainPage.InitializeComponent() in D:\code\uno\tests\tlk1194\ItemsRepeaterSelection\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainPage_0240dbe7b7b29d4de0c9e16d14bff8f5.cs:line 72
         at ItemsRepeaterSelection.MainPage..ctor() in D:\code\uno\tests\tlk1194\ItemsRepeaterSelection\MainPage.xaml.cs:line 12
         at ItemsRepeaterSelection.MetadataBuilder_611.CreateInstance() in D:\code\uno\tests\tlk1194\ItemsRepeaterSelection\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs:line 22332
         at Microsoft.UI.Xaml.Controls.Frame.CreatePageInstance(Type sourcePageType) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 475
         at Microsoft.UI.Xaml.PagePool.DequeuePage(Type pageType) in /__w/1/s/src/Uno.UI/UI/Xaml/PagePool.cs:line 69
         at Microsoft.UI.Xaml.Controls.Frame.CreatePageInstanceCached(Type sourcePageType) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 465
         at Microsoft.UI.Xaml.Controls.Frame.EnsurePageInitialized(PageStackEntry entry) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 455
         at Microsoft.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 305
         at ItemsRepeaterSelection.App.OnNavigationFailed(Object sender, NavigationFailedEventArgs e) in D:\code\uno\tests\tlk1194\ItemsRepeaterSelection\App.xaml.cs:line 61
         at Microsoft.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 309
         at Microsoft.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 285
         at Microsoft.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs:line 280
         at ItemsRepeaterSelection.App.OnLaunched(LaunchActivatedEventArgs args) in D:\code\uno\tests\tlk1194\ItemsRepeaterSelection\App.xaml.cs:line 46
         at Microsoft.UI.Xaml.Application.Initialize() in /__w/1/s/src/Uno.UI/UI/Xaml/Application.skia.cs:line 102
         at Uno.UI.Dispatching.NativeDispatcher.<>c__DisplayClass14_1.<EnqueueOperation>b__0() in /__w/1/s/src/Uno.UI.Dispatching/Native/NativeDispatcher.cs:line 255
         at Uno.UI.Dispatching.NativeDispatcher.DispatchItems() in /__w/1/s/src/Uno.UI.Dispatching/Native/NativeDispatcher.cs:line 131
```
</details>

## Expected behavior
^ should not throw any exception.

## How to reproduce it (as minimally and precisely as possible)
Nuget Package: Uno.Toolkit.WinUI@6.0.18
Affected platform(s): Windows

**Comment by Xiaoy312** [comment]
```
protected override object? ProvideValue(IXamlServiceProvider serviceProvider)
{
	if (!(serviceProvider.GetService(typeof(IProvideValueTarget)) is IProvideValueTarget provideValueTarget))
	{
		return null; // <==
```
somehow the if-condition evaluated to `true`, when it shouldn't?:
```
> serviceProvider.GetService(typeof(Microsoft.UI.Xaml.Markup.IProvideValueTarget))
{Uno.UI.Xaml.Markup.XamlServiceProviderContext}
    Microsoft.UI.Xaml.Markup.IRootObjectProvider.RootObject: '((Microsoft.UI.Xaml.Markup.IRootObjectProvider)serviceProvider.GetService(typeof(Microsoft.UI.Xaml.Markup.IProvideValueTarget))).RootObject' threw an exception of type 'System.NotImplementedException'
    Microsoft.UI.Xaml.Markup.IUriContext.BaseUri: '((Microsoft.UI.Xaml.Markup.IUriContext)serviceProvider.GetService(typeof(Microsoft.UI.Xaml.Markup.IProvideValueTarget))).BaseUri' threw an exception of type 'System.NotImplementedException'
    TargetObject: {Microsoft.UI.Xaml.Controls.Button}
    TargetProperty: {Microsoft.UI.Xaml.Markup.ProvideValueTargetProperty}
> serviceProvider.GetService(typeof(Microsoft.UI.Xaml.Markup.IProvideValueTarget)) as Microsoft.UI.Xaml.Markup.IProvideValueTarget
{Uno.UI.Xaml.Markup.XamlServiceProviderContext}
    Microsoft.UI.Xaml.Markup.IRootObjectProvider.RootObject: '((Microsoft.UI.Xaml.Markup.IRootObjectProvider)(serviceProvider.GetService(typeof(Microsoft.UI.Xaml.Markup.IProvideValueTarget)) as Microsoft.UI.Xaml.Markup.IProvideValueTarget)).RootObject' threw an exception of type 'System.NotImplementedException'
    Microsoft.UI.Xaml.Markup.IUriContext.BaseUri: '((Microsoft.UI.Xaml.Markup.IUriContext)(serviceProvider.GetService(typeof(Microsoft.UI.Xaml.Markup.IProvideValueTarget)) as Microsoft.UI.Xaml.Markup.IProvideValueTarget)).BaseUri' threw an exception of type 'System.NotImplementedException'
    TargetObject: {Microsoft.UI.Xaml.Controls.Button}
    TargetProperty: {Microsoft.UI.Xaml.Markup.ProvideValueTargetProperty}
```
even the same code, copied into a new markup doesn't produce the same result: jumping over the if-block...

**Comment by Xiaoy312** [comment]
simpler repro:
```
var xyzAB = new tlk1219.AncestralBindingExtension();
var utuAB = new Uno.Toolkit.UI.AncestorBindingExtension();

var target = new Button();
var context = MarkupHelper.CreateParserContext(null, typeof(Control), nameof(Control.IsEnabled), target.IsEnabled.GetType());

// step into each of calls below:
var xyzResult = (xyzAB as IMarkupExtensionOverrides).ProvideValue(context);
var utuResult = (utuAB as IMarkupExtensionOverrides).ProvideValue(context);

// ===
public partial class AncestralBindingExtension : MarkupExtension {
	protected override object? ProvideValue(IXamlServiceProvider serviceProvider) {
		// evaluates to false
		if (!(serviceProvider.GetService(typeof(IProvideValueTarget)) is IProvideValueTarget provideValueTarget))
		{
			// BUT the very same code in Uno.Toolkit.UI.AncestorBindingExtension, would evaluate to false, and enter here...
			return null;
		}

		// and, we reach here
		return null;
```

AncestralBindingExtension impl literally copy the first part of AncestorBindingExtension from reflection(steppable version)...
somehow they produce different outcomes..?

if we step into `XamlServiceProvidercontext::GetService(Type)`, we can see that in both cases, it returned `this` since the `Contains` returns `true`

inspecting the type being passed in, we can see that they are the same:
```
  from user space
      > actualType.FullName
      "Microsoft.UI.Xaml.Markup.IProvideValueTarget"
      > actualType.AssemblyQualifiedName
      "Microsoft.UI.Xaml.Markup.IProvideValueTarget, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null"
      > actualType.Assembly.GetCustomAttributes(typeof(System.Reflection.AssemblyInformationalVersionAttribute), true)[0]
      {System.Reflection.AssemblyInformationalVersionAttribute}
          InformationalVersion: "5.3.90+Branch.release-stable-5.3.Sha.76646d9175b1997df913bf4f4962a0958fc07586.76646d9175b1997df913bf4f4962a0958fc07586"
          TypeId: {Name = "AssemblyInformationalVersionAttribute" FullName = "System.Reflection.AssemblyInformationalVersionAttribute"}

  from toolkit invoking into uno.ui
      > type.FullName
      "Microsoft.UI.Xaml.Markup.IProvideValueTarget"
      > type.AssemblyQualifiedName
      "Microsoft.UI.Xaml.Markup.IProvideValueTarget, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null"
      > type.Assembly.GetCustomAttributes(typeof(System.Reflection.AssemblyInformationalVersionAttribute), true)[0]
      {System.Reflection.AssemblyInformationalVersionAttribute}
          InformationalVersion: "5.3.90+Branch.release-stable-5.3.Sha.76646d9175b1997df913bf4f4962a0958fc07586.76646d9175b1997df913bf4f4962a0958fc07586"
          TypeId: {Name = "AssemblyInformationalVersionAttribute" FullName = "System.Reflection.AssemblyInformationalVersionAttribute"}
```
^ which should rule out the hypothesis of mismatching signatures

**Comment by Xiaoy312** [comment]
that was stupid....
as @Youssef1313 pointed out, vs tends to often not highlight the current execution line properly... 
which i shouldve known better
vs matched over the `return null` into the next `if`...

**Comment by Xiaoy312** [comment]
the underlying bug was the same as #1218, where we were trying to cast the `null` into a `bool` via `XamlBindingHelper.ConvertValue`
