### ISSUE TITLE
[InputExtensions][Windows] AutoFocusNext/AutoFocusNextElement fails on WinUI Desktop

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.toolkit.ui#802]
1. Navigate to the InputExtensionsSamplePage in the Toolkit sample app
2. Focus on the first field
3. Press Enter
4. Crash

## Exception details:
_Catastrophic failure - **This API is not yet supported in WinUI desktop.**_

>   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Input.IFocusManagerStaticsMethods.FindNextFocusableElement(IObjectReference _obj, FocusNavigationDirection focusNavigationDirection)
   at Microsoft.UI.Xaml.Input.FocusManager.FindNextFocusableElement(FocusNavigationDirection focusNavigationDirection)
   at Uno.Toolkit.UI.InputExtensions.OnUIElementKeyUp(Object sender, KeyRoutedEventArgs e) in X:\src\uno.toolkit.ui\src\Uno.Toolkit.UI\Behaviors\InputExtensions.cs:line 165
   at WinRT._EventSource_global__Microsoft_UI_Xaml_Input_KeyEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, KeyRoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Input.KeyEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)

Looking at the [documentation for `FindNextFocusableElement`](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.focusmanager.findnextfocusableelement?view=windows-app-sdk-1.3#microsoft-ui-xaml-input-focusmanager-findnextfocusableelement(microsoft-ui-xaml-input-focusnavigationdirection-windows-foundation-rect)), I see a Remark stating: 

![image](https://github.com/unoplatform/uno.toolkit.ui/assets/4793020/074b7f5a-2725-4906-9cdd-2e629aac03bd)

If I change the call to use `FindNextElement` then I receive the following exception message:

>In a WinUI Desktop app, the app must call the FindNextElement overload with the FindNextElementOptions parameter, and the FindNextElementOptions.SearchRoot must be set to a loaded DependencyObject.]}

It seems we need to provide the `FindNextElementOptions` with a `SearchRoot` and we cannot use `FocusNavigationDirection.Next` or `FocusNavigationDirection.Previous` with the `FindNextElement` method in WinUI Desktop.

**Comment by kazo0** [comment]
cc: @MartinZikmund since you may be interested since it's focus related, only for Windows though

**Comment by MartinZikmund** [comment]
I have seen this before and I think there was a way around it, will check next week 👍
